let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_enter = 0
let g:ale_open_list = 1
"let g:ale_set_loclist = 0
"let g:ale_set_quickfix = 1
"let g:ale_linters = {'rust': ['cargo']}